name: 'hugo-algolia2'
description: 'upload hugo posts to algolia'
inputs:
  input:
    description: 'upload path'
    required: false
    default: './content/**'
  output:
    description: 'algolia.json output'
    required: false
    default: 'public/algolia.json'
  extname:
    description: 'filter extname'
    required: false
    default: '.md,.html'
  baseurl:
    description: 'base url'
    required: false
    default: '/'
  uri:
    description: 'uri format, eg. :year:month/:slug'
    required: false
    default: ':year:month/:slug'
  index:
    description: 'algolia index name'
    required: ture
  apikey:
    description: 'algolia admin key'
    required: ture
  appid:
    description: 'algolia app id'
    required: ture

runs:
  using: 'composite'
  steps:
     - run: npm install -g hugo-algolia2
       shell: bash
     - run: pwd && ls -lh
       shell: bash
     - run: hugo-algolia2 -s -i "$ALGOLIA_INPUT" -o $ALGOLIA_OUTPUT --extname $ALGOLIA_EXTNAME -b $ALGOLIA_BASEURL -u $ALGOLIA_URI -x $ALGOLIA_INDEX -k $ALGOLIA_APIKEY -a $ALGOLIA_APPID
       shell: bash
       env:
         ALGOLIA_BASEURL: ${{ inputs.baseurl }}
         ALGOLIA_URI: ${{ inputs.uri }}
         ALGOLIA_INDEX: ${{ inputs.index }}
         ALGOLIA_APIKEY: ${{ inputs.apikey }}
         ALGOLIA_APPID: ${{ inputs.appid }}
         ALGOLIA_INPUT: ${{ inputs.input }}
         ALGOLIA_OUTPUT: ${{ inputs.output }}
         ALGOLIA_EXTNAME: ${{ inputs.extname }}